name: AntiBlockPortal
main: me.ryush00.AntiBlockPortal.AntiBlockPortal
version: 0.1
commands:
   AntiBlockPortal:
      description: AntiBlockPortal command
      usage: /<command> [action]
      aliases: abp
      permission-message: You don't have <permission>